# Generated by Django 3.2.6 on 2021-09-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='name',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
