# Generated by Django 3.2.6 on 2021-09-04 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_user_blogmodel_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='email',
            new_name='user',
        ),
    ]
