# Generated by Django 3.2.6 on 2021-09-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_email_blogmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='name',
        ),
    ]
